---
- name: Create Domoticz src dir
  file:
    path: "{{ domoticz_download_dir }}/{{ domoticz_src }}"
    state: directory
    owner: "{{ domoticz_user }}"
    group: "{{ domoticz_group }}"

- name: GET Domoticz (No SSL validate due lack of SNI support)
  get_url:
    url: "{{ taskd_tarball_url }}"
    dest: "{{ domoticz_download_dir }}/{{ domoticz_src }}.tar.gz"
    validate_certs: no
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version == '7') or (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 14.04)

- name: GET Domoticz
  get_url:
    url: "{{ domoticz_url }}"
    dest: "{{ domoticz_download_dir }}/{{ domoticz_src }}.tar.gz"

- name: Unpack Domoticz source files
  unarchive:
    src: "{{ domoticz_download_dir }}/{{ domoticz_src }}.tar.gz"
    dest: "{{ domoticz_download_dir }}/{{ domoticz_src }}"
    owner: "{{ domoticz_user }}"
    group: "{{ domoticz_group }}"
    remote_src: yes

- block:
    - name: Move init script for using systemd
      template:
        src: domoticz/init-systemd.jinja2
        dest: /lib/systemd/system/domoticz.service
        owner: root
        group: root
        mode: 0775

    - name: Autostart Domoticz and restart service
      systemd:
        name: domoticz
        enabled: yes
        daemon_reload: yes
      notify: restart domoticz

  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7") or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 15.04) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8)

- block:
    - name: Setup Software Collections
      yum:
        name: centos-release-scl
        state: present

    - name: Setup Python 3.3
      yum:
        name: python33
        state: latest

    - name: Move init script Centos 6
      template:
        src: domoticz/init-centos-fedora.jinja2
        dest: /etc/init.d/domoticz
        owner: root
        group: root
        mode: 0775
      notify: restart plexpy

    - name: Autostart Plexpy and restart service
      service:
        name: plexpy
        enabled: yes
      notify: restart plexpy

  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- block:
    - name: Move init script for using init.d
      template:
        src: domoticz/init-initd.jinja2
        dest: /etc/init.d/
        owner: root
        group: root
        mode: 0775

    - name: Autostart Domoticz and restart service
      service:
        name: domoticz
        enabled: yes
      notify: restart domoticz

  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6') or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 15.10)