---
- name: Clone Domoticz repo
  git:
    repo: "{{ domoticz_url }}"
    dest: "{{ domoticz_download_dir }}/domoticz"
    version: "{{ domoticz_version }}"
  register: domoticz_clone

- block:

    - name: Cmake release
      command: cmake -DCMAKE_BUILD_TYPE=Release .
      args:
        chdir: "{{ domoticz_download_dir }}/domoticz"
        creates: "{{ domoticz_download_dir }}/domoticz/Makefile"

    - name: Make Domoticz
      command: make
      args:
        chdir: "{{ domoticz_download_dir }}/domoticz"
        creates: "{{ domoticz_download_dir }}/domoticz/domoticz"

    - block:
        - name: Move init script for using systemd
          template:
            src: domoticz/init-systemd.jinja2
            dest: /lib/systemd/system/domoticz.service
            owner: root
            group: root
            mode: 0775

        - name: Autostart Domoticz and restart service
          systemd:
            name: domoticz
            enabled: yes
            daemon_reload: yes
          notify: restart domoticz

      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7") or
            (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 15.04) or
            (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8)

    #- block:
    #    - name: Setup Software Collections
    #      yum:
    #        name: centos-release-scl
    #        state: present
    #
    #    - name: Setup Python 3.3
    #      yum:
    #        name: python33
    #        state: latest
    #
    #    - name: Move init script Centos 6
    #      template:
    #        src: domoticz/init-centos-fedora.jinja2
    #        dest: /etc/init.d/domoticz
    #        owner: root
    #        group: root
    #        mode: 0775
    #      notify: restart plexpy
    #
    #    - name: Autostart Plexpy and restart service
    #      service:
    #        name: plexpy
    #        enabled: yes
    #      notify: restart plexpy
    #
    #  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

    - block:
        - name: Move init script for using init.d
          template:
            src: domoticz/init-initd.jinja2
            dest: /etc/init.d/
            owner: root
            group: root
            mode: 0775

        - name: Autostart Domoticz and restart service
          service:
            name: domoticz
            enabled: yes
          notify: restart domoticz

      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6') or
            (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 15.10)

  when: domoticz_clone.changed