---
- name: Clone Open-ZWave repo
  git:
    repo: "{{ zwave_url }}"
    dest: "{{ domoticz_download_dir }}/open-zwave"
    version: "{{ zwave_version }}"
  register: openzwave_clone

- block:

  - name: Create symlink open-zwave-read-only
    file:
      src: "{{ domoticz_download_dir }}/open-zwave"
      dest: "{{ domoticz_download_dir }}/open-zwave-read-only"
      state: link

  - name: Make Open-ZWave
    command: make
    args:
      chdir: "{{ domoticz_download_dir }}/open-zwave"
      creates: "{{ domoticz_download_dir }}/open-zwave/MinOZW"

  when: openzwave_clone.changed