---
- name: Ensure download directory is present
  file:
    path: "{{ domoticz_download_dir }}"
    state: directory

- include_tasks: load-variables.yml
- include_tasks: setup-prerequisite.yml
- include_tasks: setup-users.yml
- include_tasks: build-zwave.yml
  when: domoticz_zwave_support
- include_tasks: build-domoticz.yml