---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: ${DEV_MOLECULE_RULES}/yaml-lint.yml

platforms:
  - name: domoticz-Debian9
    image: lansible/debian:9

  - name: domoticz-Debian8
    image: lansible/debian:8

  - name: domoticz-Ubuntu1604
    image: lansible/ubuntu:16.04

#  - name: domoticz-Ubuntu1404
#    image: lansible/ubuntu:14.04
#
#  - name: domoticz-Ubuntu1204
#    image: lansible/ubuntu:12.04

provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: ${DEV_MOLECULE_RULES}/ansible-lint.yml

scenario:
  name: default
