---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/_rules/.yamllint

platforms:
  - name: Ubuntu1404
    image: lansible/ubuntu:14.04

provisioner:
  name: ansible
  options:
    v: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  lint:
    name: ansible-lint
    options:
      c: molecule/_rules/.ansible-lint

scenario:
  name: legacy

verifier:
  name: goss
  enabled: false
